
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: RdsPsqlAzure
  description: Cloudify blueprint
  tags:
    - tosca
    - cloudify
  links:
    - url: http://52.210.80.32/console/page/blueprints_blueprint/RdsPsqlAzure?c=%5B%7B%22context%22%3A%7B%7D%7D%2C%7B%22context%22%3A%7B%22blueprintId%22%3A%22RdsPsqlAzure%22%7D%2C%22pageName%22%3A%22RdsPsqlAzure%22%7D%5D#!
      title: Deploy component
      icon: user
spec:
  type: service
  lifecycle: production
  owner: team-a
